# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python312
service: prod
instance_class: F2

entrypoint: uvicorn app:app --host 0.0.0.0 --port $PORT --loop uvloop

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.

env_variables:
  # Global variables 
  GLOBAL_EVENT_BUS: 'local'
  GLOBAL_DEBUG_MODE: 'false'
  # Gemini variables
  GEMINI_MODEL_NAME: 'gemini-2.0-flash-001'
  GEMINI_EMBEDDING_MODEL_NAME: 'text-embedding-004'
  # Vertex variables
  VERTEX_MODEL_NAME: 'gemini-2.0-flash'
  VERTEX_EMBEDDING_MODEL_NAME: 'text-embedding-005'
  VERTEX_REGION: 'us-central1'
  # Postgres variables
  POSTGRES_DB: 'deus-vult'
  POSTGRES_PORT: '5432'


handlers:
- url: /.*
  script: auto

liveness_check:
  path: "/ping"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/ping"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
