"""Initial database schema setup

Revision ID: c8ba7c7e553e
Revises:
Create Date: 2025-04-28 20:52:06.317818

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8ba7c7e553e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_game_sessions_chat_id", table_name="game_sessions")
    op.drop_index("ix_game_sessions_object_id", table_name="game_sessions")
    op.drop_table("game_sessions")
    op.drop_index("ix_primary_stats_character_id", table_name="primary_stats")
    op.drop_index("ix_primary_stats_object_id", table_name="primary_stats")
    op.drop_table("primary_stats")
    op.drop_index("ix_lore_character_id", table_name="lore")
    op.drop_index("ix_lore_object_id", table_name="lore")
    op.drop_table("lore")
    op.add_column(
        "characters",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    )
    op.add_column("characters", sa.Column("health", sa.Integer(), nullable=False))
    op.add_column("characters", sa.Column("energy", sa.Integer(), nullable=False))
    op.add_column(
        "characters", sa.Column("selected_clan_id", sa.Integer(), nullable=False)
    )
    op.drop_index("ix_characters_chat_id", table_name="characters")
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.create_index(
        op.f("ix_characters_selected_clan_id"),
        "characters",
        ["selected_clan_id"],
        unique=False,
    )
    op.drop_constraint("characters_chat_id_fkey", "characters", type_="foreignkey")
    op.create_foreign_key(
        None, "characters", "clans", ["selected_clan_id"], ["object_id"]
    )
    op.drop_column("characters", "chat_id")
    op.drop_index("idx_chats_chat_instance", table_name="chats")
    op.create_index(
        op.f("ix_chats_chat_instance"), "chats", ["chat_instance"], unique=False
    )
    op.drop_column("chats", "is_participant")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column("is_participant", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_chats_chat_instance"), table_name="chats")
    op.create_index("idx_chats_chat_instance", "chats", ["chat_instance"], unique=False)
    op.add_column(
        "characters",
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "characters", type_="foreignkey")
    op.create_foreign_key(
        "characters_chat_id_fkey", "characters", "chats", ["chat_id"], ["object_id"]
    )
    op.drop_index(op.f("ix_characters_selected_clan_id"), table_name="characters")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.create_index("ix_characters_chat_id", "characters", ["chat_id"], unique=False)
    op.drop_column("characters", "selected_clan_id")
    op.drop_column("characters", "energy")
    op.drop_column("characters", "health")
    op.drop_column("characters", "name")
    op.create_table(
        "lore",
        sa.Column("object_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("character_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("appearance", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("background", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "class_name",
            postgresql.ENUM(
                "FARMER", "PRIEST", "WARRIOR", "SCHOLAR", name="supportedclasses"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.object_id"], name="lore_character_id_fkey"
        ),
        sa.PrimaryKeyConstraint("object_id", name="lore_pkey"),
    )
    op.create_index("ix_lore_object_id", "lore", ["object_id"], unique=False)
    op.create_index("ix_lore_character_id", "lore", ["character_id"], unique=False)
    op.create_table(
        "primary_stats",
        sa.Column("object_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("character_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("strength", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("perception", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("endurance", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("charisma", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("intelligence", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("agility", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("luck", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.object_id"],
            name="primary_stats_character_id_fkey",
        ),
        sa.PrimaryKeyConstraint("object_id", name="primary_stats_pkey"),
    )
    op.create_index(
        "ix_primary_stats_object_id", "primary_stats", ["object_id"], unique=False
    )
    op.create_index(
        "ix_primary_stats_character_id", "primary_stats", ["character_id"], unique=False
    )
    op.create_table(
        "game_sessions",
        sa.Column("object_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.object_id"], name="game_sessions_chat_id_fkey"
        ),
        sa.PrimaryKeyConstraint("object_id", name="game_sessions_pkey"),
    )
    op.create_index(
        "ix_game_sessions_object_id", "game_sessions", ["object_id"], unique=False
    )
    op.create_index(
        "ix_game_sessions_chat_id", "game_sessions", ["chat_id"], unique=False
    )
    # ### end Alembic commands ###
